### ISSUE TITLE
Question re: flush()

### ISSUE THREAD

**Issue by ijcd** [lboekhorst/cloud_watch#1]
It looks like it will only flush() when the buffer is full? If there is a log entry sitting there that hasn't filled the buffer, it will sit forever? Is there any time-based flush as well?

**Comment by lboekhorst** [comment]
Thanks for calling me out on this 😄 

I have been putting this feature off for a while but I just pushed it to `master`. I will leave it running in a staging application until after the holidays to see if any issues come up and push a new version to Hex if not. If you are feeling adventurous, you can pull directly from `master`. Otherwise I will release a new version in the second week of January.

**Comment by kanishkablack** [comment]
Any update on new release

**Comment by lboekhorst** [comment]
Hi @kanishkablack, we have not seen any issues in our own apps so I have published a new version to Hex. If you have any issues, please let me know!
